name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify project structure
      run: |
        [ -f "settings.gradle" ] || { echo "❌ settings.gradle missing"; exit 1; }
        [ -f "build.gradle" ] || { echo "❌ build.gradle missing"; exit 1; }
        echo "✅ Project structure valid"

    - name: Verify Gradle Wrapper
      run: |
        mkdir -p gradle/wrapper
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "⚠️ gradle-wrapper.jar missing - downloading..."
          curl -L -o gradle/wrapper/gradle-wrapper.jar \
            https://repo.maven.apache.org/maven2/gradle/wrapper/gradle-wrapper/8.0/gradle-wrapper-8.0.jar
        fi
        java -jar gradle/wrapper/gradle-wrapper.jar --version

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: |
        [ -f "gradlew" ] || gradle wrapper --gradle-version 8.0
        chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
